[project]
name = "intro-estadistica"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.15.0",
    "pandas>=2.3.2",
]
